### ISSUE TITLE
Initial module definition

### ISSUE THREAD

**Issue by andrewholgate** [wfp/survey_manager#1]
This module is for managing surveys in Drupal 8.

It supports 2 types of surveys:

# 1. HTML

The editable HTML code allows the survey manager to insert the exact HTML which they want to appear in the outputted block of the page. The user is responible to insert an HTML link (usually provided by a third party tool) which then takes the user to the survey.

## Implementation

Ideally, this will be implemented as a Drupal block which then also allows the user decide on which pages the block appears via the block visibility settings (configurable by `Content type`, `Pages`, `Role` - as seen in block edit pages)

### Extra Fields

- [x] `Title` - the block title, displayed in the admin table (see below).
- [x] `Manage survey` - a optional URL to a third party tool in which the survey can be managed.

## Example HTML

```
<div>
  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Clipboard_01.svg/2000px-Clipboard_01.svg.png" height="60">
  <a href="https://www.research.net/r/9NGWS5R">Take the survey</a>
</div>
```

# 2. Embed code

Embed code which displays a pop-up when the user viewes the page. This embed code should be provided by a third party tool, such as Survey Monkey.

- [x] The embed code must be outputted immediately before your closing `</body>` tag of the page.

## Example Embed code

```
<script>(function(t,e,o,a){var n,s,c;t.SMCX=t.SMCX||[],e.getElementById(a)||(n=e.getElementsByTagName(o),s=n[n.length-1],c=e.createElement(o),c.type="text/javascript",c.async=!0,c.id=a,c.src=["https:"===location.protocol?"https://":"http://","widget.surveymonkey.com/collect/website/js/aYaeYN6yfTYh6U0BKmvzaSSlM2ERKx77I3_2BmatRZwl3etdb3VhPeytkooYaIm4Cu.js"].join(""),s.parentNode.insertBefore(c,s))})(window,document,"script","smcx-sdk");</script>
```

## Implementation

Ideally, this would also be implemented as a Drupal block which then also allows the user decide on which pages the block appears via the block visibility settings (configurable by `Content type`, `Pages`, `Role` - as seen in block edit pages).

### Extra Fields

- [x] `Manage survey` - a optional URL to a third party tool in which the survey can be managed.

# Administration UI

A UI which allows a user with `Administrate survey` permissions to list all of the surveys on the site.

The surveys shoud be listed in a table with the following columns:

1. `Name` - the name of the survey.
1. `Sections` - a list of the pages in which the survey is being run (visibility settings of the block)
1. `Manage` - a link to a 3rd party page (in which the survey can be managed).
1. `Type` - whether it is a `HTML` or a `Embed` survey.
1. `Status` - whether the survey is set to `active` or `inactive`

# Module Permissions

- [x] `Administrate survey`

**Comment by otarza** [comment]
There is no need for custom Title field because all blocks have Title field by default.

**Comment by otarza** [comment]
As I see we need active field to show which surveys are active on admin page,

But, What happens if survey is not marked as active but it is placed in some region (not in disabled blocks section)?

Is it shown to the user anyway?

Is this active field really needed? couldn't we just put the inactive surveys in disabled section of the blocks?
